// packages/frameworks/vue/src/renderer/GenuiRenderer.vue
<script setup lang="ts">
import { ref, watch, computed, inject, nextTick, onErrorCaptured, provide, shallowRef, toValue } from 'vue';
// @ts-ignore
import SchemaRenderer, { RENDERER_SETTINGS_KEY } from '@opentiny/tiny-schema-renderer';
import { DeltaPatcher, repairJson, RepairJsonState, type IMaterials } from '@opentiny/genui-sdk-core';
import { requiredCompleteFieldSelectors as internalRequiredCompleteFieldSelectors } from './config';
import { GENUI_MATERIALS } from '../config-provider/injection-tokens';
import type { IRendererProps } from './renderer.types';
import { cardIdSymbol } from '../chat/useChat';
import { useI18n } from '../chat/i18n';

onErrorCaptured((error) => {
  console.error('GenuiRenderer error:', error);
  return true;
});

const props = withDefaults(defineProps<IRendererProps>(), {
  isJsonComplete: true,
});

const schema = ref<any>({});
const rendererInstance = ref<SchemaRenderer | null>(null);

const callAction = (actionName: string, params: any) => {
  if (!props.customActions?.[actionName]) {
    console.warn(`Action ${actionName} not found`);
    return;
  }
  return props.customActions[actionName]?.execute(params, rendererInstance.value.getContext());
};

const injectedMaterials = inject(GENUI_MATERIALS, {});
const materials = computed(() => toValue(injectedMaterials) ?? ({} as IMaterials));
const customSettings = inject(RENDERER_SETTINGS_KEY, {});

provide(RENDERER_SETTINGS_KEY, {
  ...customSettings,
  get materials() {
    return materials.value;
  },
});

const deltaPatcher = shallowRef(null);

watch(
  () => [materials.value.requiredCompleteFieldSelectors, props.requiredCompleteFieldSelectors],
  () => {
    deltaPatcher.value = new DeltaPatcher({
      requiredCompleteFieldSelectors: [
        ...internalRequiredCompleteFieldSelectors,
        ...(materials.value.requiredCompleteFieldSelectors ?? []),
        ...(props.requiredCompleteFieldSelectors || []),
      ],
    });
  },
  { immediate: true },
);

const { t } = useI18n();

const errorSchema = {
  componentName: 'Page',
  children: [
    {
      componentName: 'Text',
      props: {
        text: t('renderer.error.displayError'),
        style: 'line-height: 40px; color: var(--tv-color-error-text)',
      },
    },
  ],
};

const isError = ref(false);

const displaySchema = computed(() => {
  if (isError.value) {
    return errorSchema;
  }
  return schema.value;
});

let updateActionTimer: any | null = null;

function updateContextAndState() {
  rendererInstance.value?.setContext({
    callAction,
  });
  rendererInstance.value?.setContext({
    [cardIdSymbol]: props.id,
  });
  rendererInstance.value?.setState(props.state || {});
}

watch(
  [() => props.content, () => props.isJsonComplete],
  ([newVal, isJsonComplete]) => {
    isError.value = false;
    let json: any = newVal;
    let isCompleted = true;
    if (typeof newVal === 'string') {
      if (newVal.trim()) {
        const { value, state } = repairJson(newVal);
        if (!value || typeof value !== 'object') {
          isError.value = true;
          return;
        }
        json = value;
        isCompleted = state === RepairJsonState.SUCCESS;
      } else {
        json = {};
      }
    } else {
      isCompleted = isJsonComplete ?? true;
    }
    if (!isCompleted && json && 'lifeCycles' in json) {
      const { lifeCycles, ...rest } = json;
      json = rest;
    }
    deltaPatcher.value.patchWithDelta(schema.value, json, isCompleted); // TODO： 速率限制
    if (!updateActionTimer) {
      updateActionTimer = nextTick(() => {
        if (!rendererInstance.value) return;
        updateContextAndState();
        updateActionTimer = null;
      });
    }
  },
  {
    immediate: true,
  },
);
// 异步组件可能在更新context时候并未ready，导致恢复会话的时候context没更新
watch(
  () => rendererInstance.value,
  (newVal) => {
    if (newVal && updateActionTimer) {
      nextTick(() => updateContextAndState());
      updateActionTimer = null;
    }
  },
  {
    immediate: true,
  },
);
</script>

<template>
  <div class="schema-render-container">
    <slot name="header" :schema="schema" :isError="isError" :isFinished="!props.generating"></slot>
    <SchemaRenderer :schema="displaySchema" ref="rendererInstance" />
    <slot name="footer" :schema="schema" :isError="isError" :isFinished="!props.generating"></slot>
  </div>
</template>

<style scoped>
@import url('./custom.css');

.schema-render-container {
  position: relative;
  color: var(--tv-color-text, #191919);
}

.schema-render-container:has(.loading-warp):after {
  display: none;
}

:deep(.loading-warp.loading-warp) {
  display: none;
}

:deep(.loading-warp .loading) {
  display: none;
}
</style>

// packages/frameworks/angular/projects/renderer/src/lib/genui-renderer.ts
import { CommonModule } from '@angular/common';
import { Component, ContentChild, Input, OnInit, SimpleChanges, TemplateRef, Type, ViewChild } from '@angular/core';
import { DeltaPatcher, repairJson, RepairJsonState } from '@opentiny/genui-sdk-core';
import { RendererMain as Renderer, Mapper, directiveMap, ModuleRef } from '@opentiny/tiny-schema-renderer-ng';
import { requiredCompleteFieldSelectors } from './config';

export const CARD_ID = Symbol('schema-card-id');
export interface ICustomAction {
  execute: (params: any, context: Record<string, any>) => any;
  [key: string]: any;
}

const errorSchema = {
  componentName: 'Page',
  children: [
    {
      componentName: 'Text',
      props: { text: 'An error occurred while rendering the schema', style: 'line-height: 40px; color: red' },
    },
  ],
};

@Component({
  selector: 'genui-renderer',
  standalone: true,
  imports: [
    CommonModule,
    Renderer,
  ],
  templateUrl: './genui-renderer.html',
  styleUrls: ['./genui-renderer.css'],
  exportAs: 'genuiRenderer',
})
export class GenuiRenderer implements OnInit {
  @ViewChild('rendererInstance', { read: Renderer }) instance?: Renderer;
  @ContentChild('header') headerTemplate?: TemplateRef<any>;
  @ContentChild('footer') footerTemplate?: TemplateRef<any>;
  @Input() id?: string;
  @Input() state?: Record<string, any>;
  @Input() generating = false;
  @Input() content: string | object = '{}';
  @Input() customDirectives?: Record<string, Type<any>> = {};
  @Input() customComponents?: Record<string, Type<any>> = {};
  @Input() customComponentsModule?: Record<string, Type<any>> = {};
  @Input() customActions?: Record<string, ICustomAction> = {};
  @Input() requiredCompleteFieldSelectors?: string[];
  @Input() isJsonComplete?: boolean;
  public isError = false;
  protected deltaPatcher: DeltaPatcher | null = null;
  protected schema: any = {};
  protected updateContextAndStateTimer: any | null = null;

  get displaySchema() {
    if (this.isError) {
      return errorSchema;
    }
    return this.schema;
  }

  callAction(actionName: string, params: any) {
    if (!this.customActions?.[actionName]) {
      console.warn(`Action ${actionName} not found`);
      return;
    }
    return this.customActions[actionName]?.execute(params, this.instance?.getContext() || {});
  }

  ngOnInit() {
    // TODO：待优化成provide inject
    this.deltaPatcher = new DeltaPatcher({
      requiredCompleteFieldSelectors: [
        ...requiredCompleteFieldSelectors,
        ...(this.requiredCompleteFieldSelectors || []),
      ]
    });
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['content'] || changes['isJsonComplete']) {
      this.processNewContent(changes['content'].currentValue);
      // 异步等待渲染器初始化context后再设置
      Promise.resolve().then(() => {
        this.keepUpdateContextAndState();
      })
    }
    if (changes['customDirectives']) {
      this.customDirectives = changes['customDirectives'].currentValue;
      if (this.customDirectives) {
        this.updateCustomDirectives(this.customDirectives);
      }
    }
    if (changes['customComponents']) {
      this.customComponents = changes['customComponents'].currentValue;
      if (this.customComponents) {
        this.updateCustomComponents(this.customComponents);
      }
    }
    if (changes['customComponentsModule']) {
      this.customComponentsModule = changes['customComponentsModule'].currentValue;
      if (this.customComponentsModule) {
        this.updateCustomComponentsModule(this.customComponentsModule);
      }
    }
  }

  protected processNewContent(newVal: string | object) {
    this.isError = false;
    let json: any = newVal;
    let isCompleted = true
    if (typeof newVal === 'string') {
      if (newVal.trim()) {
        const { value, state } = repairJson(newVal);
        if (!value) {
          this.isError = true;
          return;
        }
        json = value;
        isCompleted = state === RepairJsonState.SUCCESS;
      } else {
        json = {};
      }
    } else {
      isCompleted = this.isJsonComplete ?? true;
    }
    if (!isCompleted && json && 'lifeCycles' in json) {
      const { lifeCycles: _lifeCycles, ...rest } = json;
      json = rest;
    }
    if (this.deltaPatcher) {
      this.deltaPatcher.patchWithDelta(this.schema, json, isCompleted);
    } else {
      this.schema = json;
    }
    this.instance?.detectChanges();
  }

  protected keepUpdateContextAndState() {
    if (this.instance) {
      if (!this.updateContextAndStateTimer) {
        this.updateContextAndStateTimer = setTimeout(() => {
          this.updateContextAndState();
          this.updateContextAndStateTimer = null;
        }, 0);
      }
    }
  }

  updateContextAndState() {
    this.instance?.setContext({
      callAction: this.callAction.bind(this),
    });
    if (this.id) {
      this.instance?.setContext({
        [CARD_ID]: this.id,
      });
    }
    this.instance?.setState(this.state);
  }

  protected updateCustomDirectives(customDirectives: Record<string, Type<any>>) {
    Object.keys(customDirectives).forEach(key => {
      directiveMap[key] = customDirectives[key];
    });
  }

  protected updateCustomComponents(customComponents: Record<string, Type<any>>) {
    Object.keys(customComponents).forEach(key => {
      Mapper[key] = customComponents[key];
    });
  }

  protected updateCustomComponentsModule(customComponentsModule: Record<string, Type<any>>) {
    Object.keys(customComponentsModule).forEach(key => {
      ModuleRef[key] = customComponentsModule[key];
    });
  }
}
